Realización del la funcionalidad de consultar responsable del proyecto
AdairHdz/SPP pull request #12
Opened 2021-03-12 23:39 UTC by Martha-Miroslava

Realización del la funcionalidad de consultar responsable del proyecto

2021-03-14 01:59 UTC, YazLuna approved these changes

2021-03-14 22:25 UTC, AdairHdz requested changes

2021-03-14 22:25 UTC, AdairHdz commented on DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs
> +            Project proyecIsAssigned = ProfessionalPracticesContext.Projects.SingleOrDefault(Project => Project.ResponsibleProject.IdResponsibleProject == idResponsibleProject && Project.Status == Pr
En los repositorios no se trabaja directamente con el contexto. Se trabaja con los DbSets

2021-03-14 23:07 UTC, Martha-Miroslava commented on DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs
> +            Project proyecIsAssigned = ProfessionalPracticesContext.Projects.SingleOrDefault(Project => Project.ResponsibleProject.IdResponsibleProject == idResponsibleProject && Project.Status == Pr
Gracias, ya esta corregido.

2021-03-15 00:10 UTC, AdairHdz approved these changes

2021-03-15 00:14 UTC, YazLuna approved these changes

2021-03-15 01:04 UTC, merged