Realización de la funcionalidad eliminar responsable del proyecto
AdairHdz/SPP pull request #14
Opened 2021-03-15 05:48 UTC by Martha-Miroslava

Realización de la funcionalidad eliminar responsable del proyecto y creación de la ventana menú coordinador

2021-03-15 17:34 UTC, AdairHdz requested changes

2021-03-15 17:34 UTC, AdairHdz commented on DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs
> +            return true;
¿Siempre se devuelve true?

2021-03-15 17:34 UTC, AdairHdz commented on PresentationLayer/DeleteResponsibleProject.xaml.cs
> +                    if (isSoftDeleteResponsibleProject)
El método complete() devuelve un entero. Ese entero representa el número de filas que se alteraron en la base de datos. Puedes hacer algo como if(columnasAlteradas == 1) {return true;} return false; Lo digo porque tu método siempre devuelve true, y eso lo hace propenso a errores

2021-03-15 18:56 UTC, Martha-Miroslava commented on PresentationLayer/DeleteResponsibleProject.xaml.cs
> +                    if (isSoftDeleteResponsibleProject)
Gracias, ya esta corregido, tienes razón

2021-03-15 18:57 UTC, Martha-Miroslava commented on DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs
> +            return true;
Me confundí con el saveChanges, pero ya esta corregido.

2021-03-16 00:06 UTC, YazLuna approved these changes

2021-03-16 20:00 UTC, AdairHdz approved these changes

2021-03-16 20:00 UTC, merged