Realización del caso de uso Modificar responsable del proyecto y cambio de nombre algunas ventanas
AdairHdz/SPP pull request #16
Opened 2021-03-18 00:30 UTC by Martha-Miroslava

Realización del caso de uso Modificar responsable del proyecto y cambio de nombre algunas ventanas:
ResponsibleProjectTestConsult
ResponsibleProjectRegistry
ResponsibleProjectDeltion
ResponsibleProjectConsult

2021-03-18 19:56 UTC, YazLuna approved these changes

2021-03-18 23:54 UTC, YazLuna submitted a review, later dismissed

2021-03-20 02:04 UTC, YazLuna approved these changes

2021-03-20 04:38 UTC, AdairHdz requested changes

2021-03-20 04:38 UTC, AdairHdz commented on DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs
> +        public void UpdateResponsibleProject(ResponsibleProject responsibleProjectEdit)
No necesitabas un método para actualizar, ya te había comentado que con recuperar el objeto (digamos, con un Get()) simplemente modificabas los campos como si fuera cualquier otro objeto y luego usabas Complete().
ResponsibleProject rp = unitOfWork.ResponsibleProjects.Get("idResponsable");
rp.CampoAEditar = nuevoValor;
rp.OtroCampoAEditar = nuevoValor;
unitOfWork.Complete();
unitOfWork.Dispose();
Y ya.

2021-03-20 04:38 UTC, AdairHdz commented on DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs
> +        public void ActiveResponsibleProject(ResponsibleProject responsibleProject)
Lo mismo que en el caso anterior.

2021-03-20 05:15 UTC, Martha-Miroslava commented on DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs
> +        public void UpdateResponsibleProject(ResponsibleProject responsibleProjectEdit)
Gracias, ya esta corregido

2021-03-20 05:15 UTC, Martha-Miroslava commented on DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs
> +        public void ActiveResponsibleProject(ResponsibleProject responsibleProject)
Gracias, ya esta corregido

2021-03-20 23:37 UTC, AdairHdz approved these changes

2021-03-21 17:08 UTC, YazLuna approved these changes

2021-03-21 17:31 UTC, merged