[BR-PracticionerModification]
AdairHdz/SPP pull request #30
Opened 2021-03-31 04:29 UTC by YazLuna

Caso de uso modificar practicante

2021-03-31 04:47 UTC, Martha-Miroslava submitted a review, later dismissed

2021-03-31 16:00 UTC, AdairHdz requested changes

2021-03-31 16:00 UTC, AdairHdz commented on PresentationLayer/PracticionerModification.xaml.cs
> +			Console.WriteLine(isValid + "metodo validatedata");
Remover este código

2021-03-31 16:00 UTC, AdairHdz commented on PresentationLayer/PracticionerModification.xaml.cs
> +				Console.WriteLine(v);
Remover este código

2021-04-01 04:11 UTC, YazLuna commented on PresentationLayer/PracticionerModification.xaml.cs
> +			Console.WriteLine(isValid + "metodo validatedata");
Ya fue removido

2021-04-01 04:12 UTC, YazLuna commented on PresentationLayer/PracticionerModification.xaml.cs
> +				Console.WriteLine(v);
Ya fue removido

2021-04-01 16:21 UTC, Martha-Miroslava approved these changes

2021-04-01 23:21 UTC, AdairHdz approved these changes

2021-04-02 04:34 UTC, merged