Funcionalidad Añadí reporte parcial
AdairHdz/SPP pull request #44
Opened 2021-04-04 19:18 UTC by Martha-Miroslava

Funcionalidad Añadí reporte parcial

2021-04-04 23:08 UTC, YazLuna submitted a review, later dismissed

2021-04-05 18:09 UTC, AdairHdz requested changes

2021-04-05 18:09 UTC, AdairHdz commented on PresentationLayer/ReportAdd.xaml.cs
> +        private string route;
Recuerda que los campos llevan guión bajo

2021-04-05 18:37 UTC, Martha-Miroslava commented on PresentationLayer/ReportAdd.xaml.cs
> +        private string route;
Listo, Gracias

2021-04-05 18:41 UTC, YazLuna approved these changes

2021-04-05 20:36 UTC, AdairHdz approved these changes

2021-04-05 20:36 UTC, merged