Funcionalidad Generar reporte parcial
AdairHdz/SPP pull request #73
Opened 2021-04-18 01:05 UTC by Martha-Miroslava

Funcionalidad Generar reporte parcial

2021-04-21 14:45 UTC, AdairHdz requested changes

2021-04-21 14:45 UTC, AdairHdz commented on Utilities/PartialReportTemplate.cs
> +        /*public string P1S1 { get; set; } = null;
¿Estos comentarios se usarán para algo en un futuro? Si no, lo mejor sería quitarlos

2021-04-21 15:16 UTC, Martha-Miroslava commented on Utilities/PartialReportTemplate.cs
> +        /*public string P1S1 { get; set; } = null;
Ya esta se me paso borrarlos

2021-04-21 15:48 UTC, AdairHdz approved these changes

2021-04-22 03:59 UTC, YazLuna approved these changes

2021-04-22 04:39 UTC, merged